### ISSUE TITLE
Add `macOS` arm builds to `CI`

### ISSUE THREAD

**Issue by 05nelsonm** [toxicity-io/sqlite-mc#47]
Announcement: https://github.com/actions/runner-images/issues/8439
Blog Post: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by 05nelsonm** [comment]
It's not actually running arm. Kotlin still builds for `x86_64` and skips all arm tests

https://github.com/toxicity-io/sqlite-mc/actions/runs/6404721150/job/17386647745?pr=49

**Comment by radeva** [comment]
@05nelsonm You can try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. They are on average 2x faster and 2x cheaper than GitHub's **AND** we have a **free tier for OSS projects** (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one line of code and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers **500 mins/month of free M1 runner usage** with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hesitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)
